name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
    push:
      branches:
        - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ unpl=V2_ZzNtbRADQxF8CRVWexwMAWIKFFpLAkBGdwxEXH1KW1BmChZZclRCFnQURlRnGlgUZAIZX0ZcRxxFCEdkeRtVB2QGFl5KZ3Mldgh2VHopXAJmBBBcRFFHHH0ATlZ9GFkNYgoUXnJnRBV8OHZkexFZBWQFE11BUXMURQtHV30dWABkARBtCTlCWHUPR1N5GFoDYwoaVUpVRRRwAENdfRpsBFcA; __jdv=76161171|direct|-|none|-|1607938186075; __jdu=1606307758999370494872; areaId=4; ipLoc-djd=4-48207-0-0; PCSYCityID=CN_500000_500100_500118; user-key=259290fc-c518-42a6-be9e-464d30f7078c; shshshfpa=b2fafbc1-7153-d482-f5b6-6c42717f0fe8-1607938190; shshshfpb=wByf9QaQPSnM6oqdmTdYRJQ%3D%3D; TrackID=1co2hD1d0AsFChs8b2SNrs05OcmdlBWwGWYNtuKhKFYfjeyoVoSPEw3p3LiiOxbGm9WJ6x8UH7QhNni0QmeGZt6Bimo6pp91IPnwWHh5Wyhg; pinId=2p9BdeorYCsOFUoJSYklNA; pin=jd_NFFvzYhEWVyk; unick=jd_NFFvzYhEWVyk; ceshi3.com=000; _tp=SrXZqBtWTGfFHW9SkSyQ7Q%3D%3D; _pst=jd_NFFvzYhEWVyk; shshshfp=569afecba28b0a2ace04efb96de67523; shshshsID=be77bb7fb66f7c1a4332e34bab56a565_3_1607938244546; cn=10; __jda=122270672.1606307758999370494872.1606307758.1606307758.1607938186.1; __jdc=122270672; thor=F997C44183F73329F8C77F6B7A80B0C2F6A6EEBCD3D86FE1EB6276F78E6896984B1A82224E5DEAAB32B562A236FFBC104ED97F79F3C2A2CD4372061438A529101181E26DF23C20FD51FF1EC654B60355FF4D91F810AFAD27622CAAF39959EB6DA013B77F5754FD31735AE3D6EC88922B81F225F9A856A0C6F8F888BFB94EB4947B1E70501395B25DD37A0C944C25FC2A9CBBD7E43218339E103A6F00FF8F110C; 3AB9D23F7A4B3C9B=2UMPXXRG7O4BJM37FMEWAR7D2FVWESH72UKZRAIW32K77K5S72D3M37JA7POUSSF3BQZY44GIUISRPMD6CXMYQEWBA; __jdb=122270672.7.1606307758999370494872|1.1607938186 }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ SCU81667Tb9655065469583bc6bb85856bf2647305e41346013fc0 }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


